# Generated by Django 3.2.25 on 2024-10-18 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fyrtdhfy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free', models.ImageField(upload_to='fyrtdhfy/free/images/')),
                ('rel_user_1_1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fyrtdhfy_rel_user_1_1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
